version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  gcp-cli: circleci/gcp-cli@3.0.1
  cloudrun: circleci/gcp-cloud-run@1.0.0
jobs:
  pep8:
    docker:
      - image: circleci/python:3.10.1
    steps:
      - checkout
      - run:
          name: addFlake8
          command: "sudo pip install flake8\n"
      - run:
          name: pep8Check
          command: "sudo flake8 --max-complexity 10\n"
  build_test:
    docker:
      - image: circleci/python:3.10.1
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
  build_push_image:
    docker:
      - image: circleci/python:3.10.1
        auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build app and Docker image
          command: |
            sudo docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
            echo ${GCP_PROJECT_KEY} | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json
            echo 'export GOOGLE_CLOUD_KEYS=$(cat $HOME/gcloud-service-key.json)' >> $BASH_ENV
            echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
            echo 'export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
            ls
            docker build -t mikohei/learning_to_discordpy .
            docker run -d --name tmp mikohei/learning_to_discordpy
            sudo docker push mikohei/learning_to_discordpy
      # pyinstaller -F hello_world.py
      # - gcp-gcr/gcr-auth:
      #     gcloud-service-key: GOOGLE_CLOUD_KEYS
      #     google-project-id: GOOGLE_PROJECT_ID
      #     google-compute-zone: GOOGLE_COMPUTE_ZONE
      # - gcp-gcr/push-image:
      #     google-project-id: GOOGLE_PROJECT_ID
      #     registry-url: "us.gcr.io"
      #     image: $IMAGE_NAME
      # - cloudrun/deploy:
      #     platform: "managed"
      #     image: "us.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME"
      #     service-name: "orb-gcp-cloud-run"
      #     region: $GOOGLE_COMPUTE_ZONE
      #     unauthenticated: true
  deploy:
    executor: gcp-cli/default
    docker:
      - image: circleci/python:3.10.1
        auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - gcp-cli/setup:
          version: 404.0.0
          gcloud_service_key: GOOGLE_CLOUD_KEYS
          google_project_id: GOOGLE_PROJECT_ID
          google_compute_zone: GOOGLE_COMPUTE_ZONE
      - run:
          name: Deploy to compute engine
          command: |
            echo "hoge"
workflows:
  build_test_deploy:
    jobs:
      - pep8
      - build_test
      - build_push_image:
          requires:
            - pep8
            - build_test
      - deploy:
          requires:
            - build_push_image