version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.0
jobs:
  pep8:
    docker:
      - image: 'circleci/python:3.10.1'
    steps:
      - checkout
      - run:
          name: addFlake8
          command: "sudo pip install flake8\n"
      - run:
          name: pep8Check
          command: "sudo flake8 --max-complexity 10\n"
  build_test:
    docker:
      - image: 'circleci/python:3.10.1'
    steps:
      - checkout
      - run:
          name: 'Install Python Dependencies'
          command: "echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV\npip install --user -r requirements.txt\n"
  build_push_image_cloud_run_mangaged:
    docker:
      - image: 'circleci/python:3.10.1'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: 'Build app binary and Docker image'
          command: "echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV\necho ${GCP_PROJECT_KEY} | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json\necho 'export GOOGLE_CLOUD_KEYS=$(cat $HOME/gcloud-service-key.json)' >> $BASH_ENV\necho 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV\necho 'export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV && source $BASH_ENV\npip install --user -r requirements.txt\npyinstaller -F hello_world.py\ndocker build -t us.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME -t us.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME:$TAG .\n"
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: us.gcr.io
          image: $IMAGE_NAME
      - cloudrun/deploy:
          platform: managed
          image: us.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME
          service-name: orb-gcp-cloud-run
          region: $GOOGLE_COMPUTE_ZONE
          unauthenticated: true
workflows:
  build_test_deploy:
    jobs:
      - pep8
      - build_test
      - build_push_image_cloud_run_mangaged:
          requires:
            - build_test